import { test } from "node:test";
import assert from "node:assert/strict";
import { PGlite } from "@electric-sql/pglite";
import { readFile, readdir } from "node:fs/promises";
import { randomUUID } from "node:crypto";
import { authInput } from "../../lib/auth-input";
import { contentChanges } from "../../lib/content-diff";
import { defaultSite } from "../../lib/site/schema";
test("Google and sign-out do not require password credentials; email modes do", () => {
  assert.equal(authInput.parse({ mode: "google", email: "", password: "", next: "/app" }).mode, "google");
  assert.equal(authInput.parse({ mode: "logout" }).mode, "logout");
  assert.throws(() => authInput.parse({ mode: "signin", email: "", password: "" }));
  assert.throws(() => authInput.parse({ mode: "signup", email: "person@example.com", password: "short" }));
  assert.equal(authInput.parse({ mode: "confirmation", email: "person@example.com", next: "/start?package=first" }).mode, "confirmation");
});
test("publication review names changed fields and search visibility", () => {
  const site = defaultSite({ id: randomUUID(), name: "Studio", brief: {} });
  const next = structuredClone(site.content);
  next.fields.heading = "New heading"; next.seo.home.noindex = true;
  const changes = contentChanges(site.manifest, site.content, next);
  assert.equal(changes.length, 2);
  assert.deepEqual(changes[0], { label: "Home: Main heading", before: "Studio", after: "New heading" });
  assert.equal(changes[1].label, "Home: Search visibility");
});
test("new briefs are independent and retry safe; State drafts need explicit authorized activation", async () => {
  const db = new PGlite();
  await db.exec(`create role anon;create role authenticated;create role service_role;create schema auth;create schema storage;create table auth.users(id uuid primary key,email text);create function auth.uid() returns uuid language sql as $$select nullif(current_setting('test.uid',true),'')::uuid$$;create function auth.jwt() returns jsonb language sql as $$select '{}'::jsonb$$;create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint);`);
  for (const file of (await readdir("supabase/migrations")).filter(f => f.endsWith(".sql")).sort()) await db.exec(await readFile(`supabase/migrations/${file}`, "utf8"));
  const owner = randomUUID(), other = randomUUID(), key = randomUUID();
  await db.query("insert into auth.users(id) values($1),($2)", [owner, other]);
  await db.query("select set_config('test.uid',$1,false)", [owner]);
  const create = async (request: string) => (await db.query<any>("select create_onboarding_project($1) result", [request])).rows[0].result;
  const first = await create(key);
  assert.equal((await create(key)).id, first.id);
  assert.notEqual((await create(randomUUID())).id, first.id);
  await db.query("select set_config('test.uid',$1,false)", [other]);
  await assert.rejects(() => create(key), /not found or access denied/);
  await db.query("select set_config('test.uid',$1,false)", [owner]);
  const states = [{ id: "lunch", title: "Lunch", enabled: true, timezone: "Australia/Brisbane", days: [1,2,3,4,5], start: "11:00", end: "15:00", priority: 0, overrides: { heading: "Lunch today" } }];
  const board = (await db.query<any>("insert into boards(project_id,kind,data) values($1,'states',$2) returning *", [first.id, JSON.stringify({ objects: [], states })])).rows[0];
  const activate = (version: number, request: string) => db.query<any>("select activate_state_schedules($1,$2,$3,$4) result", [first.id, board.id, version, request]);
  await assert.rejects(() => activate(0, randomUUID()), /Pro is required/);
  await db.query("update projects set phase='LIVE',pro=true where id=$1", [first.id]);
  const activationKey = randomUUID(), release = (await activate(board.version, activationKey)).rows[0].result;
  assert.deepEqual(release.states, states);
  assert.deepEqual((await activate(board.version, activationKey)).rows[0].result, release);
  await assert.rejects(() => activate(board.version + 1, randomUUID()), /Save conflict/);
  await db.query("update boards set data=$2,version=version+1 where id=$1", [board.id, JSON.stringify({ objects: [], states: [{ ...states[0], title: "Changed draft", overrides: { heading: "Changed draft" } }] })]);
  assert.deepEqual((await activate(board.version, activationKey)).rows[0].result, release);
  assert.equal((await db.query<any>("select states from state_releases where project_id=$1", [first.id])).rows[0].states[0].title, "Lunch");
  await db.query("select set_config('test.uid',$1,false)", [other]);
  await assert.rejects(() => activate(board.version + 1, randomUUID()), /not found or access denied/);
  await db.close();
});
